### ISSUE TITLE
How can training a Swin-Transformer?

### ISSUE THREAD

**Issue by JinXins** [fistyee/MixPro#5]
**Dear author,**
&emsp;&emsp;How can i use ***MixPro*** to training a model based on **Swin-Transformer?**

**Comment by fistyee** [comment]
Thank you for your interest. The training configs are in the path MixPro/configs/swin/

**Comment by JinXins** [comment]
Dear author,
&nbsp; &nbsp; I mean when training Swin-Transformer we don't need to return *attention* to compute lambda?  I  find that configs do not set `PAL_ATTN: Ture`
